#  ===== Dev mode =====
# frontend/Dockerfile.dev
FROM node:18

WORKDIR /app

# Copy package & install
COPY package*.json ./
RUN npm install

# Copy code
COPY . .

# Expose cổng dev của Vite
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]